spring.application.name=todolist

spring.datasource.url=jdbc:postgresql://localhost:5432/todolist_db
spring.datasource.username=postgres
spring.datasource.password=1234

# Hibernate cria/atualiza as tabelas automaticamente com base nas Entities.
# Ótimo para estudo; em projetos reais, prefere-se Flyway/Liquibase (ver seção "Próximos passos").
spring.jpa.hibernate.ddl-auto=update

# Mostra o SQL gerado pelo Hibernate no console — ótimo para aprender o que está rolando por baixo dos panos
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true